correccion ortografica y del subtitulo
marcocarcamo-tech/Hyperblog pull request #1
Opened 2021-06-19 09:10 UTC by marcocarcamo-tech

Errores que no debieron pasar al main

2021-06-19 09:14 UTC, marcocarcamoo requested changes
En vez de usar acentos directos, usar una entidad HTML

2021-06-20 00:01 UTC, marcocarcamo-tech commented
Cambio hechos, hacer el pull request.

2021-06-20 00:02 UTC, marcocarcamo-tech commented
Error, hacer el merge.

2021-06-20 00:05 UTC, marcocarcamoo approved these changes
Muy bien!

2021-06-20 00:06 UTC, merged